package main

// Service description templates used by slinit-init-maker. These are
// kept as plain strings (rather than //go:embed files) so the generator
// ships as a single-file binary without any asset layout on disk.
//
// Each template receives either the full Config struct or a small
// per-service wrapper. See Plan() for the binding details.

const tmplSystemInit = `# system-init: synchronisation marker for early boot.
#
# Every other service should "depends-on: system-init" so that slinit
# has a single well-defined point at which the system is "up enough"
# to start user-visible services. This service does nothing itself.
type = internal
`

const tmplSystemMounts = `# system-mounts: brings up every filesystem in /etc/fstab that was not
# mounted by the initramfs. Uses the classic util-linux 'mount -a'.
# Feel free to replace this with explicit mount units if you prefer.
type = scripted
command = /bin/mount -a
restart = false
depends-on: system-init
`

const tmplNetwork = `# network: stub service. Replace with your own networking bring-up
# (dhcpcd, iwd, systemd-networkd-alternatives, etc.).
#
# This stub is safe: it exits 0 immediately, so 'boot' will proceed.
type = scripted
command = /bin/true
restart = false
depends-on: system-init
`

const tmplGetty = `# getty on {{.TTY}}: launches a login prompt on /dev/{{.TTY}}.
# Restarts automatically if the user logs out. Disable by deleting
# this file and the corresponding "waits-for:" line in {{.BootServiceName}}.
type = process
command = {{.GettyCmd}} --keep-baud {{.GettyBaud}} {{.TTY}} linux
restart = true
restart-delay = 1
depends-on: system-init
inittab-id = t{{.Index}}
inittab-line = {{.TTY}}
`

const tmplBoot = `# {{.BootServiceName}}: top-level boot target.
#
# This is an internal (non-executing) service whose only job is to
# express "everything that should start at boot". It uses waits-for
# rather than depends-on so that a single failing target (for example,
# a getty on a missing TTY) does not tear the entire boot down.
#
# Start slinit with:   slinit --service {{.BootServiceName}}
# or point the kernel cmdline at this service via
# "init=/sbin/slinit -- --service {{.BootServiceName}}".
type = internal
{{range .Waits}}waits-for: {{.}}
{{end}}`

const tmplEnvFile = `# env: environment variables exported to every service launched by
# slinit. Load with:   slinit --env-file /etc/slinit/boot.d/env
{{if .Hostname}}HOSTNAME={{.Hostname}}
{{end}}{{if .Timezone}}TZ={{.Timezone}}
{{end}}PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
`

const tmplShutdownHook = `#!/bin/sh
# shutdown-hook.sample — template for /etc/slinit/shutdown-hook.
#
# slinit invokes the shutdown hook (if it exists and is executable)
# after services have stopped but before swapoff/umount/remount-ro.
# The first argument is the shutdown type: reboot, halt, poweroff,
# soft, or kexec.
#
# If the hook exits 0, slinit trusts it to have handled umount and
# swapoff on its own. If the hook exits non-zero (or is missing),
# slinit performs the default cleanup.
#
# To activate this sample:
#   cp shutdown-hook.sample /etc/slinit/shutdown-hook
#   chmod +x /etc/slinit/shutdown-hook
#
# The sample is intentionally not executable by default.

set -eu
shutdown_type="${1:-halt}"

case "$shutdown_type" in
	reboot|halt|poweroff|soft|kexec)
		printf 'shutdown-hook: handling %s\n' "$shutdown_type"
		;;
	*)
		printf 'shutdown-hook: unknown type %s\n' "$shutdown_type" >&2
		exit 1
		;;
esac

# Put your cleanup commands below (sync buffers, flush application
# state, notify remote monitoring, etc.) and remove the "exit 1" line
# once you are ready to own the umount/swapoff sequence.
exit 1
`

const tmplReadme = `# slinit boot directory

This directory was generated by slinit-init-maker. It contains a
minimal but bootable slinit service layout:

- {{.BootServiceName}} — top-level internal service; start with
  ` + "`" + `slinit --service {{.BootServiceName}}` + "`" + `.
- system-init — synchronisation marker every other service depends on.
{{if .WithMounts}}- system-mounts — runs ` + "`" + `mount -a` + "`" + ` to bring up /etc/fstab.
{{end}}{{if .WithNetwork}}- network — stub network-bring-up (replace me).
{{end}}{{if gt .GettyCount 0}}- getty-tty1..{{.GettyCount}} — interactive login prompts on
  /dev/tty1..{{.GettyCount}}, launched via ` + "`" + `{{.GettyCmd}}` + "`" + `.
{{end}}- env — KEY=VALUE file with PATH/HOSTNAME/TZ; load via
  ` + "`" + `--env-file` + "`" + `.
{{if .WithShutdownHook}}- shutdown-hook.sample — template hook to run during shutdown.
{{end}}

## Wiring into the kernel command line

    init={{.SlinitBin}} -- --service {{.BootServiceName}} --env-file {{.OutputDir}}/env

## Regenerating

Re-run slinit-init-maker with ` + "`" + `--force` + "`" + ` to overwrite this directory,
or point ` + "`" + `--output` + "`" + ` at a fresh path for a side-by-side comparison.
`
