# _lib.sh — shared helpers for tests/performance/demo/*.sh harnesses.
#
# Every harness in this directory follows the same shape: inject
# perf-collect into demo/services/, patch demo/services/boot,
# rebuild the initramfs, boot QEMU N times, extract a PERF-BEGIN..
# PERF-END raw-data block from serial stdout, parse it, print
# benchstat-compatible summary lines. This file owns the pieces
# that don't vary: block extraction, /proc parsing, math, output.
#
# Sourced by cold-boot.sh, minimal-boot.sh, fork-exec-throughput.sh,
# pid1-footprint.sh. Not executable on its own.

# perf_write_collector <dst_path> <depends_on> [<pre_dump_sleep_sec>]
#   Writes a `perf-collect` slinit service file at $dst_path. The
#   service is type=scripted with the given hard dependency (typical
#   values: "all-services" for full-demo, "system-init" for minimal
#   boot, "mock-all" for fork-exec throughput). Optional 3rd arg
#   inserts `sleep N;` before the raw-data dump — used by
#   pid1-footprint.sh to let PID-1 quiesce (GC settle) before the
#   status read.
#
#   Emits raw /proc/uptime + /proc/1/status + fd count + slinit
#   size between PERF-BEGIN..PERF-END markers, buffered to
#   /tmp/perf.out then cat'd to /dev/console in one write (minimises
#   interleave with slinit's own [OK]/[STOPPD] console output), then
#   `slinitctl shutdown poweroff` for a clean QEMU exit.
#
#   The `command =` line must stay on ONE physical line (slinit's
#   config parser has no `\` continuation) and use no backslash
#   escapes / `$` variables (both get eaten at parse time).
perf_write_collector() {
    local dst=$1 dep=$2 sleep_sec=${3:-0}
    local sleep_prefix=""
    [ "$sleep_sec" -gt 0 ] && sleep_prefix="sleep ${sleep_sec}; "

    cat > "$dst" <<EOF
# perf-collect -- generated by tests/performance/demo/_lib.sh.
# See _lib.sh's perf_write_collector for details / docs.
type = scripted
depends-on: ${dep}
command = /bin/sh -c '${sleep_prefix}{ echo PERF-BEGIN; echo UPTIME:; cat /proc/uptime; echo STATUS-BEGIN; cat /proc/1/status; echo STATUS-END; echo FDS:; ls /proc/1/fd 2>/dev/null | wc -l; echo SLINIT_BYTES:; stat -c %s /sbin/slinit 2>/dev/null || echo 0; echo PERF-END; } > /tmp/perf.out 2>&1; sync; cat /tmp/perf.out > /dev/console; sync; sleep 1; slinitctl shutdown poweroff
EOF
}

# perf_extract_block <log_file>
#   Reads the QEMU serial log, extracts the PERF-BEGIN..PERF-END
#   block, strips ANSI colour escapes (slinit's [OK]/[STOPPD] can
#   interleave briefly) and \r (added by /dev/console — breaks
#   anchored patterns like /^STATUS-BEGIN$/). Prints the cleaned
#   block; empty stdout means "no block found".
perf_extract_block() {
    sed -n '/PERF-BEGIN/,/PERF-END/p' "$1" \
        | sed 's/\x1b\[[0-9;]*[a-zA-Z]//g' \
        | tr -d '\r'
}

# perf_parse_block <block>
#   Extracts BOOT_NS, RSS_KB, VMPEAK_KB, THREADS, FDS, SLINIT_BYTES
#   from a block that perf_extract_block produced. Prints
#   `NAME=value` lines suitable for `eval`. Missing fields print as
#   empty (`NAME=`) so callers can detect them.
perf_parse_block() {
    local block=$1
    local up_line status boot rss peak thr fds bin

    # /proc/uptime line follows the "UPTIME:" label. Field 1 =
    # kernel wall-clock seconds since power-on. Multiply -> ns.
    up_line=$(printf '%s\n' "$block" | awk '/^UPTIME:/{getline; print; exit}')
    boot=$(printf '%s\n' "$up_line"  | awk '{printf "%d\n", $1 * 1e9}')

    # /proc/1/status verbatim between STATUS-BEGIN..END. awk's
    # default FS collapses tab+space so $2 = numeric value.
    status=$(printf '%s\n' "$block" | sed -n '/^STATUS-BEGIN$/,/^STATUS-END$/p')
    rss=$(printf  '%s\n' "$status" | awk '/^VmRSS:/   {print $2; exit}')
    peak=$(printf '%s\n' "$status" | awk '/^VmPeak:/  {print $2; exit}')
    thr=$(printf  '%s\n' "$status" | awk '/^Threads:/ {print $2; exit}')

    # FDS + SLINIT_BYTES: value is on the line after the label.
    fds=$(printf '%s\n' "$block" | awk '/^FDS:/         {getline; print; exit}')
    bin=$(printf '%s\n' "$block" | awk '/^SLINIT_BYTES:/{getline; print; exit}')

    printf 'BOOT_NS=%s\n'      "$boot"
    printf 'RSS_KB=%s\n'       "$rss"
    printf 'VMPEAK_KB=%s\n'    "$peak"
    printf 'THREADS=%s\n'      "$thr"
    printf 'FDS=%s\n'          "$fds"
    printf 'SLINIT_BYTES=%s\n' "$bin"
    printf 'UPTIME_LINE=%q\n'  "$up_line"
}

# perf_median <n1> <n2> ...
#   Prints the median of the arguments. Numeric sort, middle-of-array
#   for odd count, average of the two middles for even count.
perf_median() {
    printf '%s\n' "$@" | sort -n | awk 'BEGIN{c=0} {a[c++]=$1} END{
        if (c%2) print a[int(c/2)]; else print (a[c/2-1]+a[c/2])/2
    }'
}

# perf_p95 <n1> <n2> ...
#   Prints the 95th-percentile value (nearest-rank).
perf_p95() {
    printf '%s\n' "$@" | sort -n | awk 'BEGIN{c=0} {a[c++]=$1} END{
        i=int(0.95*(c-1)+0.5); print a[i]
    }'
}

# perf_summary <label> <n> <total> <boot_med_ns> <boot_p95_ns> \
#              <rss_med_kb> <peak_med_kb> <bin_bytes>
#   Prints a 4-line benchstat-compatible summary for docs/PERFORMANCE.md.
perf_summary() {
    local label=$1 n=$2 total=$3 boot_med=$4 boot_p95=$5
    local rss=$6 peak=$7 bin=$8
    local boot_med_ms boot_p95_ms bin_kb

    boot_med_ms=$(awk -v b="$boot_med" 'BEGIN{printf "%.1f", b/1e6}')
    boot_p95_ms=$(awk -v b="$boot_p95" 'BEGIN{printf "%.1f", b/1e6}')
    bin_kb=$(awk       -v b="$bin"      'BEGIN{printf "%.0f", b/1024}')

    echo
    echo "=== ${label} summary (n=${n}/${total}) ==="
    printf "BenchmarkColdBoot_%-14s %3d   %s ms (p95 %s ms)\n" \
        "$label" "$n" "$boot_med_ms" "$boot_p95_ms"
    printf "BenchmarkPID1RSS_%-15s %3d   %d kB\n" \
        "$label" "$n" "$rss"
    printf "BenchmarkPID1VmPeak_%-12s %3d   %d kB\n" \
        "$label" "$n" "$peak"
    printf "BenchmarkSlinitBinarySize        1   %d kB (%d bytes)\n" \
        "$bin_kb" "$bin"
}
