//go:build linux && amd64

package seccomp

import "golang.org/x/sys/unix"

// syscallNumbers maps the systemd / strace / man-page form of a Linux
// syscall name (lowercase, underscores) onto its x86_64 number. The
// list is deliberately exhaustive enough that the predefined groups in
// groups.go resolve every entry — a missing entry would silently leave
// the syscall un-filterable, the most dangerous failure mode for a
// seccomp implementation.
//
// New entries are welcome; the rule is "if it appears in a systemd
// SystemCallFilter= group or a real-world ServiceManager filter, add
// it here." Architecture-specific syscalls live in the per-arch file.
var syscallNumbers = map[string]int{
	// I/O
	"read":      unix.SYS_READ,
	"write":     unix.SYS_WRITE,
	"open":      unix.SYS_OPEN,
	"close":     unix.SYS_CLOSE,
	"openat":    unix.SYS_OPENAT,
	"openat2":   unix.SYS_OPENAT2,
	"creat":     unix.SYS_CREAT,
	"lseek":     unix.SYS_LSEEK,
	"pread64":   unix.SYS_PREAD64,
	"pwrite64":  unix.SYS_PWRITE64,
	"readv":     unix.SYS_READV,
	"writev":    unix.SYS_WRITEV,
	"preadv":    unix.SYS_PREADV,
	"pwritev":   unix.SYS_PWRITEV,
	"preadv2":   unix.SYS_PREADV2,
	"pwritev2":  unix.SYS_PWRITEV2,
	"dup":       unix.SYS_DUP,
	"dup2":      unix.SYS_DUP2,
	"dup3":      unix.SYS_DUP3,
	"pipe":      unix.SYS_PIPE,
	"pipe2":     unix.SYS_PIPE2,
	"sendfile":  unix.SYS_SENDFILE,
	"splice":    unix.SYS_SPLICE,
	"tee":       unix.SYS_TEE,
	"vmsplice":  unix.SYS_VMSPLICE,
	"ioctl":     unix.SYS_IOCTL,
	"fcntl":     unix.SYS_FCNTL,
	"fadvise64": unix.SYS_FADVISE64,
	"fallocate": unix.SYS_FALLOCATE,

	// Stat / file metadata
	"stat":         unix.SYS_STAT,
	"fstat":        unix.SYS_FSTAT,
	"lstat":        unix.SYS_LSTAT,
	"newfstatat":   unix.SYS_NEWFSTATAT,
	"statx":        unix.SYS_STATX,
	"statfs":       unix.SYS_STATFS,
	"fstatfs":      unix.SYS_FSTATFS,
	"ustat":        unix.SYS_USTAT,
	"access":       unix.SYS_ACCESS,
	"faccessat":    unix.SYS_FACCESSAT,
	"faccessat2":   unix.SYS_FACCESSAT2,
	"getdents":     unix.SYS_GETDENTS,
	"getdents64":   unix.SYS_GETDENTS64,
	"truncate":     unix.SYS_TRUNCATE,
	"ftruncate":    unix.SYS_FTRUNCATE,
	"getcwd":       unix.SYS_GETCWD,
	"chdir":        unix.SYS_CHDIR,
	"fchdir":       unix.SYS_FCHDIR,
	"rename":       unix.SYS_RENAME,
	"renameat":     unix.SYS_RENAMEAT,
	"renameat2":    unix.SYS_RENAMEAT2,
	"mkdir":        unix.SYS_MKDIR,
	"mkdirat":      unix.SYS_MKDIRAT,
	"rmdir":        unix.SYS_RMDIR,
	"unlink":       unix.SYS_UNLINK,
	"unlinkat":     unix.SYS_UNLINKAT,
	"link":         unix.SYS_LINK,
	"linkat":       unix.SYS_LINKAT,
	"symlink":      unix.SYS_SYMLINK,
	"symlinkat":    unix.SYS_SYMLINKAT,
	"readlink":     unix.SYS_READLINK,
	"readlinkat":   unix.SYS_READLINKAT,
	"chmod":        unix.SYS_CHMOD,
	"fchmod":       unix.SYS_FCHMOD,
	"fchmodat":     unix.SYS_FCHMODAT,
	"chown":        unix.SYS_CHOWN,
	"fchown":       unix.SYS_FCHOWN,
	"lchown":       unix.SYS_LCHOWN,
	"fchownat":     unix.SYS_FCHOWNAT,
	"umask":        unix.SYS_UMASK,
	"sync":         unix.SYS_SYNC,
	"syncfs":       unix.SYS_SYNCFS,
	"fsync":        unix.SYS_FSYNC,
	"fdatasync":    unix.SYS_FDATASYNC,
	"sync_file_range": unix.SYS_SYNC_FILE_RANGE,

	// Memory
	"brk":            unix.SYS_BRK,
	"mmap":           unix.SYS_MMAP,
	"munmap":         unix.SYS_MUNMAP,
	"mremap":         unix.SYS_MREMAP,
	"mprotect":       unix.SYS_MPROTECT,
	"madvise":        unix.SYS_MADVISE,
	"mlock":          unix.SYS_MLOCK,
	"mlock2":         unix.SYS_MLOCK2,
	"munlock":        unix.SYS_MUNLOCK,
	"mlockall":       unix.SYS_MLOCKALL,
	"munlockall":     unix.SYS_MUNLOCKALL,
	"mincore":        unix.SYS_MINCORE,
	"msync":          unix.SYS_MSYNC,
	"memfd_create":   unix.SYS_MEMFD_CREATE,
	"copy_file_range": unix.SYS_COPY_FILE_RANGE,

	// Process / thread
	"fork":              unix.SYS_FORK,
	"vfork":             unix.SYS_VFORK,
	"clone":             unix.SYS_CLONE,
	"clone3":            unix.SYS_CLONE3,
	"execve":            unix.SYS_EXECVE,
	"execveat":          unix.SYS_EXECVEAT,
	"exit":              unix.SYS_EXIT,
	"exit_group":        unix.SYS_EXIT_GROUP,
	"wait4":             unix.SYS_WAIT4,
	"waitid":            unix.SYS_WAITID,
	"getpid":            unix.SYS_GETPID,
	"getppid":           unix.SYS_GETPPID,
	"gettid":            unix.SYS_GETTID,
	"getpgid":           unix.SYS_GETPGID,
	"getpgrp":           unix.SYS_GETPGRP,
	"setsid":            unix.SYS_SETSID,
	"getsid":            unix.SYS_GETSID,
	"setpgid":           unix.SYS_SETPGID,
	"pidfd_open":        unix.SYS_PIDFD_OPEN,
	"pidfd_send_signal": unix.SYS_PIDFD_SEND_SIGNAL,
	"pidfd_getfd":       unix.SYS_PIDFD_GETFD,

	// Signals
	"kill":              unix.SYS_KILL,
	"tgkill":            unix.SYS_TGKILL,
	"tkill":             unix.SYS_TKILL,
	"rt_sigaction":      unix.SYS_RT_SIGACTION,
	"rt_sigprocmask":    unix.SYS_RT_SIGPROCMASK,
	"rt_sigreturn":      unix.SYS_RT_SIGRETURN,
	"rt_sigpending":     unix.SYS_RT_SIGPENDING,
	"rt_sigtimedwait":   unix.SYS_RT_SIGTIMEDWAIT,
	"rt_sigsuspend":     unix.SYS_RT_SIGSUSPEND,
	"rt_sigqueueinfo":   unix.SYS_RT_SIGQUEUEINFO,
	"rt_tgsigqueueinfo": unix.SYS_RT_TGSIGQUEUEINFO,
	"sigaltstack":       unix.SYS_SIGALTSTACK,
	"signalfd":          unix.SYS_SIGNALFD,
	"signalfd4":         unix.SYS_SIGNALFD4,
	"pause":             unix.SYS_PAUSE,

	// Credentials
	"getuid":      unix.SYS_GETUID,
	"geteuid":     unix.SYS_GETEUID,
	"getgid":      unix.SYS_GETGID,
	"getegid":     unix.SYS_GETEGID,
	"getgroups":   unix.SYS_GETGROUPS,
	"setuid":      unix.SYS_SETUID,
	"setgid":      unix.SYS_SETGID,
	"setreuid":    unix.SYS_SETREUID,
	"setregid":    unix.SYS_SETREGID,
	"setresuid":   unix.SYS_SETRESUID,
	"setresgid":   unix.SYS_SETRESGID,
	"getresuid":   unix.SYS_GETRESUID,
	"getresgid":   unix.SYS_GETRESGID,
	"setfsuid":    unix.SYS_SETFSUID,
	"setfsgid":    unix.SYS_SETFSGID,
	"setgroups":   unix.SYS_SETGROUPS,
	"capget":      unix.SYS_CAPGET,
	"capset":      unix.SYS_CAPSET,

	// Time
	"clock_gettime":   unix.SYS_CLOCK_GETTIME,
	"clock_getres":    unix.SYS_CLOCK_GETRES,
	"clock_nanosleep": unix.SYS_CLOCK_NANOSLEEP,
	"clock_settime":   unix.SYS_CLOCK_SETTIME,
	"clock_adjtime":   unix.SYS_CLOCK_ADJTIME,
	"settimeofday":    unix.SYS_SETTIMEOFDAY,
	"gettimeofday":    unix.SYS_GETTIMEOFDAY,
	"adjtimex":        unix.SYS_ADJTIMEX,
	"time":            unix.SYS_TIME,
	"nanosleep":       unix.SYS_NANOSLEEP,
	"alarm":           unix.SYS_ALARM,
	"setitimer":       unix.SYS_SETITIMER,
	"getitimer":       unix.SYS_GETITIMER,
	"timer_create":    unix.SYS_TIMER_CREATE,
	"timer_settime":   unix.SYS_TIMER_SETTIME,
	"timer_gettime":   unix.SYS_TIMER_GETTIME,
	"timer_delete":    unix.SYS_TIMER_DELETE,
	"timer_getoverrun": unix.SYS_TIMER_GETOVERRUN,
	"timerfd_create":  unix.SYS_TIMERFD_CREATE,
	"timerfd_settime": unix.SYS_TIMERFD_SETTIME,
	"timerfd_gettime": unix.SYS_TIMERFD_GETTIME,

	// Polling / events
	"poll":           unix.SYS_POLL,
	"ppoll":          unix.SYS_PPOLL,
	"select":         unix.SYS_SELECT,
	"pselect6":       unix.SYS_PSELECT6,
	"epoll_create":   unix.SYS_EPOLL_CREATE,
	"epoll_create1":  unix.SYS_EPOLL_CREATE1,
	"epoll_ctl":      unix.SYS_EPOLL_CTL,
	"epoll_wait":     unix.SYS_EPOLL_WAIT,
	"epoll_pwait":    unix.SYS_EPOLL_PWAIT,
	"epoll_pwait2":   unix.SYS_EPOLL_PWAIT2,
	"eventfd":        unix.SYS_EVENTFD,
	"eventfd2":       unix.SYS_EVENTFD2,
	"inotify_init":   unix.SYS_INOTIFY_INIT,
	"inotify_init1":  unix.SYS_INOTIFY_INIT1,
	"inotify_add_watch": unix.SYS_INOTIFY_ADD_WATCH,
	"inotify_rm_watch":  unix.SYS_INOTIFY_RM_WATCH,
	"fanotify_init":  unix.SYS_FANOTIFY_INIT,
	"fanotify_mark":  unix.SYS_FANOTIFY_MARK,

	// Sockets / network
	"socket":      unix.SYS_SOCKET,
	"socketpair":  unix.SYS_SOCKETPAIR,
	"bind":        unix.SYS_BIND,
	"listen":      unix.SYS_LISTEN,
	"accept":      unix.SYS_ACCEPT,
	"accept4":     unix.SYS_ACCEPT4,
	"connect":     unix.SYS_CONNECT,
	"getsockname": unix.SYS_GETSOCKNAME,
	"getpeername": unix.SYS_GETPEERNAME,
	"sendto":      unix.SYS_SENDTO,
	"sendmsg":     unix.SYS_SENDMSG,
	"sendmmsg":    unix.SYS_SENDMMSG,
	"recvfrom":    unix.SYS_RECVFROM,
	"recvmsg":     unix.SYS_RECVMSG,
	"recvmmsg":    unix.SYS_RECVMMSG,
	"shutdown":    unix.SYS_SHUTDOWN,
	"setsockopt":  unix.SYS_SETSOCKOPT,
	"getsockopt":  unix.SYS_GETSOCKOPT,

	// IPC
	"shmget":    unix.SYS_SHMGET,
	"shmat":     unix.SYS_SHMAT,
	"shmdt":     unix.SYS_SHMDT,
	"shmctl":    unix.SYS_SHMCTL,
	"semget":    unix.SYS_SEMGET,
	"semop":     unix.SYS_SEMOP,
	"semctl":    unix.SYS_SEMCTL,
	"semtimedop": unix.SYS_SEMTIMEDOP,
	"msgget":    unix.SYS_MSGGET,
	"msgsnd":    unix.SYS_MSGSND,
	"msgrcv":    unix.SYS_MSGRCV,
	"msgctl":    unix.SYS_MSGCTL,
	"mq_open":   unix.SYS_MQ_OPEN,
	"mq_unlink": unix.SYS_MQ_UNLINK,
	"mq_timedsend":    unix.SYS_MQ_TIMEDSEND,
	"mq_timedreceive": unix.SYS_MQ_TIMEDRECEIVE,
	"mq_notify":       unix.SYS_MQ_NOTIFY,
	"mq_getsetattr":   unix.SYS_MQ_GETSETATTR,

	// Scheduling
	"sched_yield":          unix.SYS_SCHED_YIELD,
	"sched_setparam":       unix.SYS_SCHED_SETPARAM,
	"sched_getparam":       unix.SYS_SCHED_GETPARAM,
	"sched_setscheduler":   unix.SYS_SCHED_SETSCHEDULER,
	"sched_getscheduler":   unix.SYS_SCHED_GETSCHEDULER,
	"sched_get_priority_max": unix.SYS_SCHED_GET_PRIORITY_MAX,
	"sched_get_priority_min": unix.SYS_SCHED_GET_PRIORITY_MIN,
	"sched_rr_get_interval":  unix.SYS_SCHED_RR_GET_INTERVAL,
	"sched_setaffinity":      unix.SYS_SCHED_SETAFFINITY,
	"sched_getaffinity":      unix.SYS_SCHED_GETAFFINITY,
	"sched_setattr":          unix.SYS_SCHED_SETATTR,
	"sched_getattr":          unix.SYS_SCHED_GETATTR,

	// Random / misc
	"getrandom":  unix.SYS_GETRANDOM,
	"uname":      unix.SYS_UNAME,
	"sysinfo":    unix.SYS_SYSINFO,
	"prctl":      unix.SYS_PRCTL,
	"arch_prctl": unix.SYS_ARCH_PRCTL,
	"futex":      unix.SYS_FUTEX,
	"set_tid_address": unix.SYS_SET_TID_ADDRESS,
	"set_robust_list": unix.SYS_SET_ROBUST_LIST,
	"get_robust_list": unix.SYS_GET_ROBUST_LIST,
	"getrusage":  unix.SYS_GETRUSAGE,
	"prlimit64":  unix.SYS_PRLIMIT64,
	"getrlimit":  unix.SYS_GETRLIMIT,
	"setrlimit":  unix.SYS_SETRLIMIT,
	"getpriority": unix.SYS_GETPRIORITY,
	"setpriority": unix.SYS_SETPRIORITY,
	"ioprio_get": unix.SYS_IOPRIO_GET,
	"ioprio_set": unix.SYS_IOPRIO_SET,
	"membarrier": unix.SYS_MEMBARRIER,
	"rseq":       unix.SYS_RSEQ,
	"close_range": unix.SYS_CLOSE_RANGE,

	// Privileged
	"mount":            unix.SYS_MOUNT,
	"umount2":          unix.SYS_UMOUNT2,
	// Post-2019 filesystem-mount API. Needed for restrict-file-systems,
	// which denies every mount syscall (classic BPF can't inspect the
	// fsname string; the BPF-LSM path is systemd-specific).
	"fsopen":           unix.SYS_FSOPEN,
	"fsconfig":         unix.SYS_FSCONFIG,
	"fsmount":          unix.SYS_FSMOUNT,
	"fspick":           unix.SYS_FSPICK,
	"move_mount":       unix.SYS_MOVE_MOUNT,
	"open_tree":        unix.SYS_OPEN_TREE,
	"pivot_root":       unix.SYS_PIVOT_ROOT,
	"chroot":           unix.SYS_CHROOT,
	"setns":            unix.SYS_SETNS,
	"unshare":          unix.SYS_UNSHARE,
	"reboot":           unix.SYS_REBOOT,
	"kexec_load":       unix.SYS_KEXEC_LOAD,
	"kexec_file_load":  unix.SYS_KEXEC_FILE_LOAD,
	"sethostname":      unix.SYS_SETHOSTNAME,
	"setdomainname":    unix.SYS_SETDOMAINNAME,
	"iopl":             unix.SYS_IOPL,
	"ioperm":           unix.SYS_IOPERM,
	"swapon":           unix.SYS_SWAPON,
	"swapoff":          unix.SYS_SWAPOFF,
	"syslog":           unix.SYS_SYSLOG,
	"acct":             unix.SYS_ACCT,
	"ptrace":           unix.SYS_PTRACE,
	"process_vm_readv": unix.SYS_PROCESS_VM_READV,
	"process_vm_writev": unix.SYS_PROCESS_VM_WRITEV,
	"perf_event_open":  unix.SYS_PERF_EVENT_OPEN,
	"bpf":              unix.SYS_BPF,
	"userfaultfd":      unix.SYS_USERFAULTFD,
	"kcmp":             unix.SYS_KCMP,
	"init_module":      unix.SYS_INIT_MODULE,
	"finit_module":     unix.SYS_FINIT_MODULE,
	"delete_module":    unix.SYS_DELETE_MODULE,
	"mknod":            unix.SYS_MKNOD,
	"mknodat":          unix.SYS_MKNODAT,
	"quotactl":         unix.SYS_QUOTACTL,
}

// SyscallNumber returns the x86_64 syscall number for name. The bool is
// false when the name is unknown so callers can validate at parse time
// rather than silently dropping the entry.
func SyscallNumber(name string) (int, bool) {
	n, ok := syscallNumbers[name]
	return n, ok
}

// allSyscalls returns the full known syscall name → number map. Used by
// tests to enumerate; production callers go through SyscallNumber.
func allSyscalls() map[string]int { return syscallNumbers }
