# Bash completion for slinitctl
# Generated by: slinitctl completion bash
# Or source this file directly: source completions/slinitctl.bash

_slinitctl_commands() {
    echo "list ls start wake stop release restart status is-started is-failed shutdown trigger untrigger signal reload unload boot-time analyze catlog setenv unsetenv getallenv setenv-global unsetenv-global getallenv-global add-dep rm-dep unpin enable disable query-name service-dirs load-mech dependents"
}

_slinitctl_global_flags() {
    echo "--socket-path -p --system -s --user -u --no-wait --pin --force -f --ignore-unstarted --offline -o --services-dir -d --from --use-passed-cfd --quiet -q --help -h --version"
}

_slinitctl_shutdown_types() {
    echo "halt poweroff reboot kexec softreboot"
}

_slinitctl_dep_types() {
    echo "regular waits-for milestone soft before after"
}

_slinitctl_signals() {
    echo "SIGHUP SIGINT SIGQUIT SIGKILL SIGUSR1 SIGUSR2 SIGTERM SIGCONT SIGSTOP SIGTSTP HUP INT QUIT KILL USR1 USR2 TERM CONT STOP TSTP 1 2 3 9 10 12 15 18 19 20"
}

# List running services by querying slinitctl list.
# Falls back to empty if the daemon is unreachable.
_slinitctl_services() {
    local sock_args=""
    local i
    for ((i=1; i < COMP_CWORD; i++)); do
        case "${COMP_WORDS[i]}" in
            --system|-s) sock_args="--system" ;;
            --user|-u)   sock_args="--user" ;;
            --socket-path|-p)
                if [ $((i+1)) -lt $COMP_CWORD ]; then
                    sock_args="--socket-path ${COMP_WORDS[$((i+1))]}"
                fi
                ;;
        esac
    done
    # shellcheck disable=SC2086
    slinitctl $sock_args list 2>/dev/null | sed 's/^\[.*\] //' | sed 's/ (.*//'
}

_slinitctl() {
    local cur prev cmd
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # Find the subcommand
    cmd=""
    local i
    for ((i=1; i < COMP_CWORD; i++)); do
        case "${COMP_WORDS[i]}" in
            --socket-path|-p|--services-dir|-d|--from)
                ((i++))  # skip argument
                ;;
            -*)
                ;;
            *)
                cmd="${COMP_WORDS[i]}"
                break
                ;;
        esac
    done

    # Complete flag arguments
    case "$prev" in
        --socket-path|-p)
            COMPREPLY=( $(compgen -f -- "$cur") )
            return 0
            ;;
        --services-dir|-d)
            COMPREPLY=( $(compgen -d -- "$cur") )
            return 0
            ;;
        --from)
            COMPREPLY=( $(compgen -W "$(_slinitctl_services)" -- "$cur") )
            return 0
            ;;
    esac

    # No subcommand yet — complete flags or commands
    if [ -z "$cmd" ]; then
        if [[ "$cur" == -* ]]; then
            COMPREPLY=( $(compgen -W "$(_slinitctl_global_flags)" -- "$cur") )
        else
            COMPREPLY=( $(compgen -W "$(_slinitctl_commands)" -- "$cur") )
        fi
        return 0
    fi

    # Subcommand-specific completions
    case "$cmd" in
        start|stop|wake|release|restart|status|is-started|is-failed|\
        trigger|untrigger|reload|unload|unpin|enable|disable|\
        query-name|getallenv|catlog|dependents)
            COMPREPLY=( $(compgen -W "$(_slinitctl_services)" -- "$cur") )
            ;;
        shutdown)
            COMPREPLY=( $(compgen -W "$(_slinitctl_shutdown_types)" -- "$cur") )
            ;;
        signal)
            # First arg after signal = signal name, second = service
            local args_after_cmd=0
            for ((i=i+1; i < COMP_CWORD; i++)); do
                case "${COMP_WORDS[i]}" in
                    -*) ;;
                    *)  ((args_after_cmd++)) ;;
                esac
            done
            if [ "$args_after_cmd" -eq 0 ]; then
                if [[ "$cur" == -* ]]; then
                    COMPREPLY=( $(compgen -W "--list -l" -- "$cur") )
                else
                    COMPREPLY=( $(compgen -W "$(_slinitctl_signals)" -- "$cur") )
                fi
            else
                COMPREPLY=( $(compgen -W "$(_slinitctl_services)" -- "$cur") )
            fi
            ;;
        setenv|unsetenv)
            # First arg = service name
            local args_after_cmd=0
            for ((i=i+1; i < COMP_CWORD; i++)); do
                case "${COMP_WORDS[i]}" in
                    -*) ;;
                    *)  ((args_after_cmd++)) ;;
                esac
            done
            if [ "$args_after_cmd" -eq 0 ]; then
                COMPREPLY=( $(compgen -W "$(_slinitctl_services)" -- "$cur") )
            fi
            ;;
        add-dep|rm-dep)
            # add-dep <from> <dep-type> <to>
            local args_after_cmd=0
            for ((i=i+1; i < COMP_CWORD; i++)); do
                case "${COMP_WORDS[i]}" in
                    -*) ;;
                    *)  ((args_after_cmd++)) ;;
                esac
            done
            case "$args_after_cmd" in
                0) COMPREPLY=( $(compgen -W "$(_slinitctl_services)" -- "$cur") ) ;;
                1) COMPREPLY=( $(compgen -W "$(_slinitctl_dep_types)" -- "$cur") ) ;;
                2) COMPREPLY=( $(compgen -W "$(_slinitctl_services)" -- "$cur") ) ;;
            esac
            ;;
        list|ls|boot-time|analyze|service-dirs|load-mech|\
        setenv-global|unsetenv-global|getallenv-global)
            # No further arguments needed
            ;;
    esac

    return 0
}

complete -F _slinitctl slinitctl
