#!/bin/bash
# build.sh - Build slinit QEMU demo environment
# Downloads Alpine Linux minirootfs, compiles slinit static binaries,
# and creates a bootable initramfs image.
set -euo pipefail

# Alpine Linux configuration
ALPINE_VERSION="3.21"
ALPINE_RELEASE="3.21.6"
ALPINE_ARCH="x86_64"
ALPINE_MIRROR="https://dl-cdn.alpinelinux.org/alpine"
MINIROOTFS_URL="${ALPINE_MIRROR}/v${ALPINE_VERSION}/releases/${ALPINE_ARCH}/alpine-minirootfs-${ALPINE_RELEASE}-${ALPINE_ARCH}.tar.gz"
KERNEL_URL="${ALPINE_MIRROR}/v${ALPINE_VERSION}/releases/${ALPINE_ARCH}/netboot/vmlinuz-virt"
PACKAGES_URL="${ALPINE_MIRROR}/v${ALPINE_VERSION}/main/${ALPINE_ARCH}"

# Bash and its dependencies (Alpine APK filenames)
BASH_PKG="bash-5.2.37-r0.apk"
READLINE_PKG="readline-8.2.13-r0.apk"
LIBNCURSESW_PKG="libncursesw-6.5_p20241006-r3.apk"
NCURSES_TERMINFO_PKG="ncurses-terminfo-base-6.5_p20241006-r3.apk"

# Directories
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
BUILD_DIR="${SCRIPT_DIR}/_build"
ROOTFS_DIR="${BUILD_DIR}/rootfs"
CACHE_DIR="${SCRIPT_DIR}/_cache"
OUTPUT_DIR="${SCRIPT_DIR}/_output"

mkdir -p "${CACHE_DIR}" "${BUILD_DIR}" "${OUTPUT_DIR}"

# Step 1: Download Alpine minirootfs
ROOTFS_TAR="${CACHE_DIR}/alpine-minirootfs-${ALPINE_RELEASE}-${ALPINE_ARCH}.tar.gz"
if [ ! -f "${ROOTFS_TAR}" ]; then
    echo "[1/7] Downloading Alpine minirootfs ${ALPINE_RELEASE}..."
    curl -fSL -o "${ROOTFS_TAR}.tmp" "${MINIROOTFS_URL}"
    mv "${ROOTFS_TAR}.tmp" "${ROOTFS_TAR}"
else
    echo "[1/7] Using cached Alpine minirootfs"
fi

# Step 2: Download Alpine virt kernel
KERNEL="${CACHE_DIR}/vmlinuz-virt"
if [ ! -f "${KERNEL}" ]; then
    echo "[2/7] Downloading Alpine virt kernel..."
    curl -fSL -o "${KERNEL}.tmp" "${KERNEL_URL}"
    mv "${KERNEL}.tmp" "${KERNEL}"
else
    echo "[2/7] Using cached kernel"
fi

# Step 3: Download bash and dependencies (APK packages)
echo "[3/7] Downloading bash packages..."
for pkg in "${BASH_PKG}" "${READLINE_PKG}" "${LIBNCURSESW_PKG}" "${NCURSES_TERMINFO_PKG}"; do
    if [ ! -f "${CACHE_DIR}/${pkg}" ]; then
        echo "  Fetching ${pkg}..."
        curl -fSL -o "${CACHE_DIR}/${pkg}.tmp" "${PACKAGES_URL}/${pkg}"
        mv "${CACHE_DIR}/${pkg}.tmp" "${CACHE_DIR}/${pkg}"
    else
        echo "  Using cached ${pkg}"
    fi
done

# Step 4: Build slinit and slinitctl (static)
echo "[4/7] Building slinit and slinitctl (static)..."
cd "${PROJECT_DIR}"
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags='-s -w' -o "${BUILD_DIR}/slinit" ./cmd/slinit
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags='-s -w' -o "${BUILD_DIR}/slinitctl" ./cmd/slinitctl

# Step 5: Prepare rootfs
echo "[5/7] Preparing rootfs..."
rm -rf "${ROOTFS_DIR}"
mkdir -p "${ROOTFS_DIR}"

# Extract Alpine minirootfs
tar xzf "${ROOTFS_TAR}" -C "${ROOTFS_DIR}"

# Install bash and dependencies from APK packages
# Alpine APK files are gzipped tars; extract directly into rootfs
for pkg in "${NCURSES_TERMINFO_PKG}" "${LIBNCURSESW_PKG}" "${READLINE_PKG}" "${BASH_PKG}"; do
    tar xzf "${CACHE_DIR}/${pkg}" -C "${ROOTFS_DIR}" 2>/dev/null || true
done
# Clean up APK metadata extracted into rootfs
rm -rf "${ROOTFS_DIR}/.PKGINFO" "${ROOTFS_DIR}/.SIGN."* "${ROOTFS_DIR}/.post-install" "${ROOTFS_DIR}/.pre-install" "${ROOTFS_DIR}/.trigger"

# Install slinit binaries
install -m 755 "${BUILD_DIR}/slinit" "${ROOTFS_DIR}/sbin/slinit"
install -m 755 "${BUILD_DIR}/slinitctl" "${ROOTFS_DIR}/usr/bin/slinitctl"

# Make slinit the init system
ln -sf slinit "${ROOTFS_DIR}/sbin/init"

# Ensure directories exist
mkdir -p "${ROOTFS_DIR}/run"
mkdir -p "${ROOTFS_DIR}/dev"
mkdir -p "${ROOTFS_DIR}/proc"
mkdir -p "${ROOTFS_DIR}/sys"

# Step 6: Install service files and shell completions
echo "[6/7] Installing service files and shell completions..."
mkdir -p "${ROOTFS_DIR}/etc/slinit.d"
cp "${SCRIPT_DIR}/services/"* "${ROOTFS_DIR}/etc/slinit.d/"

# Install bash completion (generated by slinitctl itself)
mkdir -p "${ROOTFS_DIR}/etc/bash_completion.d"
"${BUILD_DIR}/slinitctl" completion bash > "${ROOTFS_DIR}/etc/bash_completion.d/slinitctl" 2>/dev/null || true

# Source completion from /etc/profile.d so interactive shells pick it up
mkdir -p "${ROOTFS_DIR}/etc/profile.d"
cat > "${ROOTFS_DIR}/etc/profile.d/slinitctl-completion.sh" <<'EOF'
# slinitctl bash completion
# Works with bash; ash/busybox sh does not support programmable completion.
# For ash, use: slinitctl <TAB> relies on the shell's default path completion.
if type complete >/dev/null 2>&1 && [ -f /etc/bash_completion.d/slinitctl ]; then
    . /etc/bash_completion.d/slinitctl
fi
EOF

# Step 7: Create initramfs
echo "[7/7] Creating initramfs..."
cd "${ROOTFS_DIR}"
find . | cpio -o -H newc 2>/dev/null | gzip > "${OUTPUT_DIR}/initramfs.cpio.gz"
cp "${KERNEL}" "${OUTPUT_DIR}/vmlinuz-virt"

echo ""
echo "Build complete!"
echo "  Kernel:    ${OUTPUT_DIR}/vmlinuz-virt"
echo "  Initramfs: ${OUTPUT_DIR}/initramfs.cpio.gz"
echo ""
echo "Run with: ./run.sh"
